; Auto-generated. Do not edit!


(cl:in-package usv_sim-msg)


;//! \htmlinclude PathPlannerFeedback.msg.html

(cl:defclass <PathPlannerFeedback> (roslisp-msg-protocol:ros-message)
  ((elapsed_time
    :reader elapsed_time
    :initarg :elapsed_time
    :type cl:float
    :initform 0.0))
)

(cl:defclass PathPlannerFeedback (<PathPlannerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PathPlannerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PathPlannerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name usv_sim-msg:<PathPlannerFeedback> is deprecated: use usv_sim-msg:PathPlannerFeedback instead.")))

(cl:ensure-generic-function 'elapsed_time-val :lambda-list '(m))
(cl:defmethod elapsed_time-val ((m <PathPlannerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader usv_sim-msg:elapsed_time-val is deprecated.  Use usv_sim-msg:elapsed_time instead.")
  (elapsed_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PathPlannerFeedback>) ostream)
  "Serializes a message object of type '<PathPlannerFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'elapsed_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PathPlannerFeedback>) istream)
  "Deserializes a message object of type '<PathPlannerFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'elapsed_time) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PathPlannerFeedback>)))
  "Returns string type for a message object of type '<PathPlannerFeedback>"
  "usv_sim/PathPlannerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PathPlannerFeedback)))
  "Returns string type for a message object of type 'PathPlannerFeedback"
  "usv_sim/PathPlannerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PathPlannerFeedback>)))
  "Returns md5sum for a message object of type '<PathPlannerFeedback>"
  "96ca6b8721a8bce34666176d169ab1f0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PathPlannerFeedback)))
  "Returns md5sum for a message object of type 'PathPlannerFeedback"
  "96ca6b8721a8bce34666176d169ab1f0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PathPlannerFeedback>)))
  "Returns full string definition for message of type '<PathPlannerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%float64 elapsed_time~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PathPlannerFeedback)))
  "Returns full string definition for message of type 'PathPlannerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%float64 elapsed_time~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PathPlannerFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PathPlannerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PathPlannerFeedback
    (cl:cons ':elapsed_time (elapsed_time msg))
))
