; Auto-generated. Do not edit!


(cl:in-package usv_sim-msg)


;//! \htmlinclude WaypointTrackingResult.msg.html

(cl:defclass <WaypointTrackingResult> (roslisp-msg-protocol:ros-message)
  ((final_wpt
    :reader final_wpt
    :initarg :final_wpt
    :type cl:integer
    :initform 0))
)

(cl:defclass WaypointTrackingResult (<WaypointTrackingResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WaypointTrackingResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WaypointTrackingResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name usv_sim-msg:<WaypointTrackingResult> is deprecated: use usv_sim-msg:WaypointTrackingResult instead.")))

(cl:ensure-generic-function 'final_wpt-val :lambda-list '(m))
(cl:defmethod final_wpt-val ((m <WaypointTrackingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader usv_sim-msg:final_wpt-val is deprecated.  Use usv_sim-msg:final_wpt instead.")
  (final_wpt m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WaypointTrackingResult>) ostream)
  "Serializes a message object of type '<WaypointTrackingResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'final_wpt)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'final_wpt)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'final_wpt)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'final_wpt)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WaypointTrackingResult>) istream)
  "Deserializes a message object of type '<WaypointTrackingResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'final_wpt)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'final_wpt)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'final_wpt)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'final_wpt)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WaypointTrackingResult>)))
  "Returns string type for a message object of type '<WaypointTrackingResult>"
  "usv_sim/WaypointTrackingResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WaypointTrackingResult)))
  "Returns string type for a message object of type 'WaypointTrackingResult"
  "usv_sim/WaypointTrackingResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WaypointTrackingResult>)))
  "Returns md5sum for a message object of type '<WaypointTrackingResult>"
  "7065bcd2aab1ea016ba8ab483931c6aa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WaypointTrackingResult)))
  "Returns md5sum for a message object of type 'WaypointTrackingResult"
  "7065bcd2aab1ea016ba8ab483931c6aa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WaypointTrackingResult>)))
  "Returns full string definition for message of type '<WaypointTrackingResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%uint32 final_wpt~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WaypointTrackingResult)))
  "Returns full string definition for message of type 'WaypointTrackingResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%uint32 final_wpt~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WaypointTrackingResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WaypointTrackingResult>))
  "Converts a ROS message object to a list"
  (cl:list 'WaypointTrackingResult
    (cl:cons ':final_wpt (final_wpt msg))
))
