// Generated by gencpp from file usv_towing/control.msg
// DO NOT EDIT!


#ifndef USV_TOWING_MESSAGE_CONTROL_H
#define USV_TOWING_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usv_towing
{
template <class ContainerAllocator>
struct control_
{
  typedef control_<ContainerAllocator> Type;

  control_()
    : surge(0.0)
    , sway(0.0)
    , yaw(0.0)  {
    }
  control_(const ContainerAllocator& _alloc)
    : surge(0.0)
    , sway(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _surge_type;
  _surge_type surge;

   typedef double _sway_type;
  _sway_type sway;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::usv_towing::control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_towing::control_<ContainerAllocator> const> ConstPtr;

}; // struct control_

typedef ::usv_towing::control_<std::allocator<void> > control;

typedef boost::shared_ptr< ::usv_towing::control > controlPtr;
typedef boost::shared_ptr< ::usv_towing::control const> controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_towing::control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_towing::control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace usv_towing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'usv_towing': ['/home/jiangxvv/catkin_ws/src/catkin_ws/src/usv_towing/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::usv_towing::control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_towing::control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_towing::control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_towing::control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_towing::control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_towing::control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_towing::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d86ccd8ad254d064df2af607e63b6ac0";
  }

  static const char* value(const ::usv_towing::control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd86ccd8ad254d064ULL;
  static const uint64_t static_value2 = 0xdf2af607e63b6ac0ULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_towing::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_towing/control";
  }

  static const char* value(const ::usv_towing::control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_towing::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 surge\n\
float64 sway\n\
float64 yaw\n\
";
  }

  static const char* value(const ::usv_towing::control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_towing::control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.surge);
      stream.next(m.sway);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_towing::control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_towing::control_<ContainerAllocator>& v)
  {
    s << indent << "surge: ";
    Printer<double>::stream(s, indent + "  ", v.surge);
    s << indent << "sway: ";
    Printer<double>::stream(s, indent + "  ", v.sway);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_TOWING_MESSAGE_CONTROL_H
