// Auto-generated. Do not edit!

// (in-package usv_sim.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PathPlannerGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.start_pose = null;
      this.start_vel = null;
      this.end_pose = null;
    }
    else {
      if (initObj.hasOwnProperty('start_pose')) {
        this.start_pose = initObj.start_pose
      }
      else {
        this.start_pose = [];
      }
      if (initObj.hasOwnProperty('start_vel')) {
        this.start_vel = initObj.start_vel
      }
      else {
        this.start_vel = [];
      }
      if (initObj.hasOwnProperty('end_pose')) {
        this.end_pose = initObj.end_pose
      }
      else {
        this.end_pose = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PathPlannerGoal
    // Serialize message field [start_pose]
    bufferOffset = _arraySerializer.float64(obj.start_pose, buffer, bufferOffset, null);
    // Serialize message field [start_vel]
    bufferOffset = _arraySerializer.float64(obj.start_vel, buffer, bufferOffset, null);
    // Serialize message field [end_pose]
    bufferOffset = _arraySerializer.float64(obj.end_pose, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PathPlannerGoal
    let len;
    let data = new PathPlannerGoal(null);
    // Deserialize message field [start_pose]
    data.start_pose = _arrayDeserializer.float64(buffer, bufferOffset, null)
    // Deserialize message field [start_vel]
    data.start_vel = _arrayDeserializer.float64(buffer, bufferOffset, null)
    // Deserialize message field [end_pose]
    data.end_pose = _arrayDeserializer.float64(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 8 * object.start_pose.length;
    length += 8 * object.start_vel.length;
    length += 8 * object.end_pose.length;
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'usv_sim/PathPlannerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '87cf7bdada84db78bc034034d07024b6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal definition
    float64[] start_pose
    float64[] start_vel
    float64[] end_pose
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PathPlannerGoal(null);
    if (msg.start_pose !== undefined) {
      resolved.start_pose = msg.start_pose;
    }
    else {
      resolved.start_pose = []
    }

    if (msg.start_vel !== undefined) {
      resolved.start_vel = msg.start_vel;
    }
    else {
      resolved.start_vel = []
    }

    if (msg.end_pose !== undefined) {
      resolved.end_pose = msg.end_pose;
    }
    else {
      resolved.end_pose = []
    }

    return resolved;
    }
};

module.exports = PathPlannerGoal;
