// Auto-generated. Do not edit!

// (in-package usv_sim.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class WaypointTrackingResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.final_wpt = null;
    }
    else {
      if (initObj.hasOwnProperty('final_wpt')) {
        this.final_wpt = initObj.final_wpt
      }
      else {
        this.final_wpt = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type WaypointTrackingResult
    // Serialize message field [final_wpt]
    bufferOffset = _serializer.uint32(obj.final_wpt, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type WaypointTrackingResult
    let len;
    let data = new WaypointTrackingResult(null);
    // Deserialize message field [final_wpt]
    data.final_wpt = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'usv_sim/WaypointTrackingResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '7065bcd2aab1ea016ba8ab483931c6aa';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # result definition
    uint32 final_wpt
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new WaypointTrackingResult(null);
    if (msg.final_wpt !== undefined) {
      resolved.final_wpt = msg.final_wpt;
    }
    else {
      resolved.final_wpt = 0
    }

    return resolved;
    }
};

module.exports = WaypointTrackingResult;
