// Auto-generated. Do not edit!

// (in-package usv_sim.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class WaypointTrackingGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.pos_x = null;
      this.pos_y = null;
      this.heading = null;
      this.mission_type = null;
      this.mission_duration = null;
    }
    else {
      if (initObj.hasOwnProperty('pos_x')) {
        this.pos_x = initObj.pos_x
      }
      else {
        this.pos_x = [];
      }
      if (initObj.hasOwnProperty('pos_y')) {
        this.pos_y = initObj.pos_y
      }
      else {
        this.pos_y = [];
      }
      if (initObj.hasOwnProperty('heading')) {
        this.heading = initObj.heading
      }
      else {
        this.heading = [];
      }
      if (initObj.hasOwnProperty('mission_type')) {
        this.mission_type = initObj.mission_type
      }
      else {
        this.mission_type = false;
      }
      if (initObj.hasOwnProperty('mission_duration')) {
        this.mission_duration = initObj.mission_duration
      }
      else {
        this.mission_duration = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type WaypointTrackingGoal
    // Serialize message field [pos_x]
    bufferOffset = _arraySerializer.float64(obj.pos_x, buffer, bufferOffset, null);
    // Serialize message field [pos_y]
    bufferOffset = _arraySerializer.float64(obj.pos_y, buffer, bufferOffset, null);
    // Serialize message field [heading]
    bufferOffset = _arraySerializer.float64(obj.heading, buffer, bufferOffset, null);
    // Serialize message field [mission_type]
    bufferOffset = _serializer.bool(obj.mission_type, buffer, bufferOffset);
    // Serialize message field [mission_duration]
    bufferOffset = _serializer.float64(obj.mission_duration, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type WaypointTrackingGoal
    let len;
    let data = new WaypointTrackingGoal(null);
    // Deserialize message field [pos_x]
    data.pos_x = _arrayDeserializer.float64(buffer, bufferOffset, null)
    // Deserialize message field [pos_y]
    data.pos_y = _arrayDeserializer.float64(buffer, bufferOffset, null)
    // Deserialize message field [heading]
    data.heading = _arrayDeserializer.float64(buffer, bufferOffset, null)
    // Deserialize message field [mission_type]
    data.mission_type = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [mission_duration]
    data.mission_duration = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 8 * object.pos_x.length;
    length += 8 * object.pos_y.length;
    length += 8 * object.heading.length;
    return length + 21;
  }

  static datatype() {
    // Returns string type for a message object
    return 'usv_sim/WaypointTrackingGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8ec2419d2a0aec459c39bee2c36ebd66';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal definition
    float64[] pos_x
    float64[] pos_y
    float64[] heading
    bool mission_type
    float64 mission_duration
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new WaypointTrackingGoal(null);
    if (msg.pos_x !== undefined) {
      resolved.pos_x = msg.pos_x;
    }
    else {
      resolved.pos_x = []
    }

    if (msg.pos_y !== undefined) {
      resolved.pos_y = msg.pos_y;
    }
    else {
      resolved.pos_y = []
    }

    if (msg.heading !== undefined) {
      resolved.heading = msg.heading;
    }
    else {
      resolved.heading = []
    }

    if (msg.mission_type !== undefined) {
      resolved.mission_type = msg.mission_type;
    }
    else {
      resolved.mission_type = false
    }

    if (msg.mission_duration !== undefined) {
      resolved.mission_duration = msg.mission_duration;
    }
    else {
      resolved.mission_duration = 0.0
    }

    return resolved;
    }
};

module.exports = WaypointTrackingGoal;
