// Generated by gencpp from file usv_sim/actuator.msg
// DO NOT EDIT!


#ifndef USV_SIM_MESSAGE_ACTUATOR_H
#define USV_SIM_MESSAGE_ACTUATOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usv_sim
{
template <class ContainerAllocator>
struct actuator_
{
  typedef actuator_<ContainerAllocator> Type;

  actuator_()
    : T_p(0.0)
    , Alpha_p(0.0)
    , T_s(0.0)
    , Alpha_s(0.0)  {
    }
  actuator_(const ContainerAllocator& _alloc)
    : T_p(0.0)
    , Alpha_p(0.0)
    , T_s(0.0)
    , Alpha_s(0.0)  {
  (void)_alloc;
    }



   typedef double _T_p_type;
  _T_p_type T_p;

   typedef double _Alpha_p_type;
  _Alpha_p_type Alpha_p;

   typedef double _T_s_type;
  _T_s_type T_s;

   typedef double _Alpha_s_type;
  _Alpha_s_type Alpha_s;





  typedef boost::shared_ptr< ::usv_sim::actuator_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_sim::actuator_<ContainerAllocator> const> ConstPtr;

}; // struct actuator_

typedef ::usv_sim::actuator_<std::allocator<void> > actuator;

typedef boost::shared_ptr< ::usv_sim::actuator > actuatorPtr;
typedef boost::shared_ptr< ::usv_sim::actuator const> actuatorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_sim::actuator_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_sim::actuator_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace usv_sim

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'usv_sim': ['/home/jiangxvv/catkin_ws/src/catkin_ws/src/bobli1987-autonomous_tugboat-a80163bcc2ef/usv_sim/msg', '/home/jiangxvv/catkin_ws/devel/share/usv_sim/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::usv_sim::actuator_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_sim::actuator_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_sim::actuator_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_sim::actuator_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_sim::actuator_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_sim::actuator_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_sim::actuator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "058476a8fb2069bcb447843b2fbad502";
  }

  static const char* value(const ::usv_sim::actuator_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x058476a8fb2069bcULL;
  static const uint64_t static_value2 = 0xb447843b2fbad502ULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_sim::actuator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_sim/actuator";
  }

  static const char* value(const ::usv_sim::actuator_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_sim::actuator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 T_p\n\
float64 Alpha_p\n\
float64 T_s\n\
float64 Alpha_s\n\
";
  }

  static const char* value(const ::usv_sim::actuator_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_sim::actuator_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.T_p);
      stream.next(m.Alpha_p);
      stream.next(m.T_s);
      stream.next(m.Alpha_s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct actuator_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_sim::actuator_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_sim::actuator_<ContainerAllocator>& v)
  {
    s << indent << "T_p: ";
    Printer<double>::stream(s, indent + "  ", v.T_p);
    s << indent << "Alpha_p: ";
    Printer<double>::stream(s, indent + "  ", v.Alpha_p);
    s << indent << "T_s: ";
    Printer<double>::stream(s, indent + "  ", v.T_s);
    s << indent << "Alpha_s: ";
    Printer<double>::stream(s, indent + "  ", v.Alpha_s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_SIM_MESSAGE_ACTUATOR_H
