// Generated by gencpp from file usv_sim/course.msg
// DO NOT EDIT!


#ifndef USV_SIM_MESSAGE_COURSE_H
#define USV_SIM_MESSAGE_COURSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usv_sim
{
template <class ContainerAllocator>
struct course_
{
  typedef course_<ContainerAllocator> Type;

  course_()
    : angle(0.0)
    , rate(0.0)
    , acceleration(0.0)  {
    }
  course_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , rate(0.0)
    , acceleration(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _rate_type;
  _rate_type rate;

   typedef double _acceleration_type;
  _acceleration_type acceleration;





  typedef boost::shared_ptr< ::usv_sim::course_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_sim::course_<ContainerAllocator> const> ConstPtr;

}; // struct course_

typedef ::usv_sim::course_<std::allocator<void> > course;

typedef boost::shared_ptr< ::usv_sim::course > coursePtr;
typedef boost::shared_ptr< ::usv_sim::course const> courseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_sim::course_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_sim::course_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace usv_sim

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'usv_sim': ['/home/jiangxvv/catkin_ws/src/catkin_ws/src/bobli1987-autonomous_tugboat-a80163bcc2ef/usv_sim/msg', '/home/jiangxvv/catkin_ws/devel/share/usv_sim/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::usv_sim::course_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_sim::course_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_sim::course_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_sim::course_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_sim::course_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_sim::course_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_sim::course_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae838d50ec8e47c9ce31d29911fbe48c";
  }

  static const char* value(const ::usv_sim::course_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae838d50ec8e47c9ULL;
  static const uint64_t static_value2 = 0xce31d29911fbe48cULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_sim::course_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_sim/course";
  }

  static const char* value(const ::usv_sim::course_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_sim::course_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n\
float64 rate\n\
float64 acceleration\n\
";
  }

  static const char* value(const ::usv_sim::course_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_sim::course_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.rate);
      stream.next(m.acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct course_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_sim::course_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_sim::course_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "rate: ";
    Printer<double>::stream(s, indent + "  ", v.rate);
    s << indent << "acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_SIM_MESSAGE_COURSE_H
