// Generated by gencpp from file usv_sim/obstacleRequest.msg
// DO NOT EDIT!


#ifndef USV_SIM_MESSAGE_OBSTACLEREQUEST_H
#define USV_SIM_MESSAGE_OBSTACLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usv_sim
{
template <class ContainerAllocator>
struct obstacleRequest_
{
  typedef obstacleRequest_<ContainerAllocator> Type;

  obstacleRequest_()
    : x_coor(0.0)
    , y_coor(0.0)
    , radius(0.0)  {
    }
  obstacleRequest_(const ContainerAllocator& _alloc)
    : x_coor(0.0)
    , y_coor(0.0)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef double _x_coor_type;
  _x_coor_type x_coor;

   typedef double _y_coor_type;
  _y_coor_type y_coor;

   typedef double _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::usv_sim::obstacleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_sim::obstacleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct obstacleRequest_

typedef ::usv_sim::obstacleRequest_<std::allocator<void> > obstacleRequest;

typedef boost::shared_ptr< ::usv_sim::obstacleRequest > obstacleRequestPtr;
typedef boost::shared_ptr< ::usv_sim::obstacleRequest const> obstacleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_sim::obstacleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_sim::obstacleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace usv_sim

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'usv_sim': ['/home/jiangxvv/catkin_ws/src/catkin_ws/src/bobli1987-autonomous_tugboat-a80163bcc2ef/usv_sim/msg', '/home/jiangxvv/catkin_ws/devel/share/usv_sim/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::usv_sim::obstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_sim::obstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_sim::obstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_sim::obstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_sim::obstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_sim::obstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_sim::obstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a876fe65406998e7960f3ccc4c14ca1";
  }

  static const char* value(const ::usv_sim::obstacleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a876fe65406998eULL;
  static const uint64_t static_value2 = 0x7960f3ccc4c14ca1ULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_sim::obstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_sim/obstacleRequest";
  }

  static const char* value(const ::usv_sim::obstacleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_sim::obstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x_coor\n\
float64 y_coor\n\
float64 radius\n\
";
  }

  static const char* value(const ::usv_sim::obstacleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_sim::obstacleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_coor);
      stream.next(m.y_coor);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obstacleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_sim::obstacleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_sim::obstacleRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_coor: ";
    Printer<double>::stream(s, indent + "  ", v.x_coor);
    s << indent << "y_coor: ";
    Printer<double>::stream(s, indent + "  ", v.y_coor);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_SIM_MESSAGE_OBSTACLEREQUEST_H
