// Generated by gencpp from file usv_sim/PathPlannerGoal.msg
// DO NOT EDIT!


#ifndef USV_SIM_MESSAGE_PATHPLANNERGOAL_H
#define USV_SIM_MESSAGE_PATHPLANNERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usv_sim
{
template <class ContainerAllocator>
struct PathPlannerGoal_
{
  typedef PathPlannerGoal_<ContainerAllocator> Type;

  PathPlannerGoal_()
    : start_pose()
    , start_vel()
    , end_pose()  {
    }
  PathPlannerGoal_(const ContainerAllocator& _alloc)
    : start_pose(_alloc)
    , start_vel(_alloc)
    , end_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _start_pose_type;
  _start_pose_type start_pose;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _start_vel_type;
  _start_vel_type start_vel;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _end_pose_type;
  _end_pose_type end_pose;





  typedef boost::shared_ptr< ::usv_sim::PathPlannerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_sim::PathPlannerGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PathPlannerGoal_

typedef ::usv_sim::PathPlannerGoal_<std::allocator<void> > PathPlannerGoal;

typedef boost::shared_ptr< ::usv_sim::PathPlannerGoal > PathPlannerGoalPtr;
typedef boost::shared_ptr< ::usv_sim::PathPlannerGoal const> PathPlannerGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_sim::PathPlannerGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_sim::PathPlannerGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace usv_sim

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'usv_sim': ['/home/jiangxvv/catkin_ws/src/catkin_ws/src/bobli1987-autonomous_tugboat-a80163bcc2ef/usv_sim/msg', '/home/jiangxvv/catkin_ws/devel/share/usv_sim/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::usv_sim::PathPlannerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_sim::PathPlannerGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_sim::PathPlannerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_sim::PathPlannerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_sim::PathPlannerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_sim::PathPlannerGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_sim::PathPlannerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87cf7bdada84db78bc034034d07024b6";
  }

  static const char* value(const ::usv_sim::PathPlannerGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87cf7bdada84db78ULL;
  static const uint64_t static_value2 = 0xbc034034d07024b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_sim::PathPlannerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_sim/PathPlannerGoal";
  }

  static const char* value(const ::usv_sim::PathPlannerGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_sim::PathPlannerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal definition\n\
float64[] start_pose\n\
float64[] start_vel\n\
float64[] end_pose\n\
";
  }

  static const char* value(const ::usv_sim::PathPlannerGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_sim::PathPlannerGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_pose);
      stream.next(m.start_vel);
      stream.next(m.end_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathPlannerGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_sim::PathPlannerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_sim::PathPlannerGoal_<ContainerAllocator>& v)
  {
    s << indent << "start_pose[]" << std::endl;
    for (size_t i = 0; i < v.start_pose.size(); ++i)
    {
      s << indent << "  start_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.start_pose[i]);
    }
    s << indent << "start_vel[]" << std::endl;
    for (size_t i = 0; i < v.start_vel.size(); ++i)
    {
      s << indent << "  start_vel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.start_vel[i]);
    }
    s << indent << "end_pose[]" << std::endl;
    for (size_t i = 0; i < v.end_pose.size(); ++i)
    {
      s << indent << "  end_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.end_pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_SIM_MESSAGE_PATHPLANNERGOAL_H
