// Generated by gencpp from file usv_sim/waypoint.msg
// DO NOT EDIT!


#ifndef USV_SIM_MESSAGE_WAYPOINT_H
#define USV_SIM_MESSAGE_WAYPOINT_H

#include <ros/service_traits.h>


#include <usv_sim/waypointRequest.h>
#include <usv_sim/waypointResponse.h>


namespace usv_sim
{

struct waypoint
{

typedef waypointRequest Request;
typedef waypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct waypoint
} // namespace usv_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::usv_sim::waypoint > {
  static const char* value()
  {
    return "2dfba887f0d6c81636f47bdde25045e3";
  }

  static const char* value(const ::usv_sim::waypoint&) { return value(); }
};

template<>
struct DataType< ::usv_sim::waypoint > {
  static const char* value()
  {
    return "usv_sim/waypoint";
  }

  static const char* value(const ::usv_sim::waypoint&) { return value(); }
};


// service_traits::MD5Sum< ::usv_sim::waypointRequest> should match 
// service_traits::MD5Sum< ::usv_sim::waypoint > 
template<>
struct MD5Sum< ::usv_sim::waypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::usv_sim::waypoint >::value();
  }
  static const char* value(const ::usv_sim::waypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::usv_sim::waypointRequest> should match 
// service_traits::DataType< ::usv_sim::waypoint > 
template<>
struct DataType< ::usv_sim::waypointRequest>
{
  static const char* value()
  {
    return DataType< ::usv_sim::waypoint >::value();
  }
  static const char* value(const ::usv_sim::waypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::usv_sim::waypointResponse> should match 
// service_traits::MD5Sum< ::usv_sim::waypoint > 
template<>
struct MD5Sum< ::usv_sim::waypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::usv_sim::waypoint >::value();
  }
  static const char* value(const ::usv_sim::waypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::usv_sim::waypointResponse> should match 
// service_traits::DataType< ::usv_sim::waypoint > 
template<>
struct DataType< ::usv_sim::waypointResponse>
{
  static const char* value()
  {
    return DataType< ::usv_sim::waypoint >::value();
  }
  static const char* value(const ::usv_sim::waypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // USV_SIM_MESSAGE_WAYPOINT_H
