// Generated by gencpp from file gnc_msgs/MotionStamped.msg
// DO NOT EDIT!


#ifndef GNC_MSGS_MESSAGE_MOTIONSTAMPED_H
#define GNC_MSGS_MESSAGE_MOTIONSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace gnc_msgs
{
template <class ContainerAllocator>
struct MotionStamped_
{
  typedef MotionStamped_<ContainerAllocator> Type;

  MotionStamped_()
    : time(0.0)
    , pose()
    , vel()
    , accel()  {
    }
  MotionStamped_(const ContainerAllocator& _alloc)
    : time(0.0)
    , pose(_alloc)
    , vel(_alloc)
    , accel(_alloc)  {
  (void)_alloc;
    }



   typedef float _time_type;
  _time_type time;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _vel_type;
  _vel_type vel;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _accel_type;
  _accel_type accel;





  typedef boost::shared_ptr< ::gnc_msgs::MotionStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnc_msgs::MotionStamped_<ContainerAllocator> const> ConstPtr;

}; // struct MotionStamped_

typedef ::gnc_msgs::MotionStamped_<std::allocator<void> > MotionStamped;

typedef boost::shared_ptr< ::gnc_msgs::MotionStamped > MotionStampedPtr;
typedef boost::shared_ptr< ::gnc_msgs::MotionStamped const> MotionStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnc_msgs::MotionStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnc_msgs::MotionStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gnc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gnc_msgs': ['/home/jiangxvv/catkin_ws/src/gnc_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gnc_msgs::MotionStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnc_msgs::MotionStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnc_msgs::MotionStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnc_msgs::MotionStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnc_msgs::MotionStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnc_msgs::MotionStamped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnc_msgs::MotionStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6633c63ac0d3fdc5b4d6fb7666e8181";
  }

  static const char* value(const ::gnc_msgs::MotionStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6633c63ac0d3fdcULL;
  static const uint64_t static_value2 = 0x5b4d6fb7666e8181ULL;
};

template<class ContainerAllocator>
struct DataType< ::gnc_msgs::MotionStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnc_msgs/MotionStamped";
  }

  static const char* value(const ::gnc_msgs::MotionStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnc_msgs::MotionStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 time\n\
geometry_msgs/Vector3 pose\n\
geometry_msgs/Vector3  vel\n\
geometry_msgs/Vector3  accel\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::gnc_msgs::MotionStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnc_msgs::MotionStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.pose);
      stream.next(m.vel);
      stream.next(m.accel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnc_msgs::MotionStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnc_msgs::MotionStamped_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.vel);
    s << indent << "accel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.accel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNC_MSGS_MESSAGE_MOTIONSTAMPED_H
